main: mytime1.cpp usetime1.cpp \
      mytime2.cpp usetime2.cpp \
      mytime3.cpp usetime3.cpp \
      vector.h vector.cpp 
	g++ mytime1.cpp usetime1.cpp -o 1.out
	g++ mytime2.cpp usetime2.cpp -o 2.out
	g++ mytime3.cpp usetime3.cpp -o 3.out
	g++ mytime3.cpp usetime3.cpp -o 3.out
clean:
	rm -f *.out


